[package]
name = "plugin-calc"
version = "0.2.0"
edition = "2024"

[lib]
name = "plugin_calc"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
evalexpr = "13"
k-launcher-domain = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
k-launcher-domain = { workspace = true }
tokio = { workspace = true }
