[package]
name = "k-launcher-ui"
version = "0.2.1"
edition = "2024"

[lib]
name = "k_launcher_ui"
path = "src/lib.rs"

[dependencies]
iced = { version = "0.14", default-features = false, features = ["image", "svg", "tokio", "tiny-skia", "wayland", "x11", "crisp", "web-colors", "thread-pool"] }
k-launcher-config = { workspace = true }
k-launcher-domain = { workspace = true }
k-launcher-kernel = { workspace = true }
k-launcher-os-bridge = { workspace = true }
k-launcher-ui-core = { workspace = true }
tokio = { workspace = true }
