[package]
name = "k-launcher-config"
version = "0.2.1"
edition = "2024"

[lib]
name = "k_launcher_config"
path = "src/lib.rs"

[dependencies]
dirs = { workspace = true }
k-launcher-domain = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = "1.0"
tracing = { workspace = true }

[dev-dependencies]
toml = "1.0"
