[package]
name = "k-launcher"
version = "0.1.0"
edition = "2024"
default-run = "k-launcher"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3

[[bin]]
name = "k-launcher"
path = "src/main.rs"

[[bin]]
name = "k-launcher-egui"
path = "src/main_egui.rs"
required-features = ["egui"]

[features]
egui = ["dep:k-launcher-ui-egui"]

[dependencies]
iced = { workspace = true }
k-launcher-config = { path = "../k-launcher-config" }
k-launcher-kernel = { path = "../k-launcher-kernel" }
k-launcher-plugin-host = { path = "../k-launcher-plugin-host" }
k-launcher-os-bridge = { path = "../k-launcher-os-bridge" }
k-launcher-ui = { path = "../k-launcher-ui" }
k-launcher-ui-egui = { path = "../k-launcher-ui-egui", optional = true }
plugin-apps = { path = "../plugins/plugin-apps" }
plugin-calc = { path = "../plugins/plugin-calc" }
plugin-cmd = { path = "../plugins/plugin-cmd" }
plugin-files = { path = "../plugins/plugin-files" }
dirs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
