[package]
name = "k-launcher"
version = "0.2.1"
edition = "2024"
default-run = "k-launcher"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3

[[bin]]
name = "k-launcher"
path = "src/main.rs"

[[bin]]
name = "k-launcher-egui"
path = "src/main_egui.rs"
required-features = ["egui"]

[features]
egui = ["dep:k-launcher-ui-egui"]

[dependencies]
k-launcher-config = { workspace = true }
k-launcher-kernel = { workspace = true }
k-launcher-domain = { workspace = true }
k-launcher-plugin-host = { workspace = true }
k-launcher-os-bridge = { workspace = true }
k-launcher-ui = { workspace = true }
k-launcher-ui-egui = { workspace = true, optional = true }
plugin-apps = { workspace = true }
plugin-calc = { workspace = true }
plugin-cmd = { workspace = true }
plugin-files = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ctrlc = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
