[package]
name = "k-launcher"
version = "0.1.0"
edition = "2024"
default-run = "k-launcher"

[[bin]]
name = "k-launcher"
path = "src/main.rs"

[dependencies]
iced = { workspace = true }
k-launcher-kernel = { path = "../k-launcher-kernel" }
k-launcher-os-bridge = { path = "../k-launcher-os-bridge" }
k-launcher-ui = { path = "../k-launcher-ui" }
plugin-apps = { path = "../plugins/plugin-apps" }
plugin-calc = { path = "../plugins/plugin-calc" }
plugin-cmd = { path = "../plugins/plugin-cmd" }
plugin-files = { path = "../plugins/plugin-files" }
tokio = { workspace = true }
