[package]
name = "plugin-files"
version = "0.2.1"
edition = "2024"

[lib]
name = "plugin_files"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
k-launcher-domain = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
k-launcher-domain = { workspace = true }
tokio = { workspace = true }
