[package]
name = "k-launcher-ui-egui"
version = "0.1.0"
edition = "2024"

[lib]
name = "k_launcher_ui_egui"
path = "src/lib.rs"

[dependencies]
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "wayland", "x11", "glow"] }
egui = "0.31"
k-launcher-config = { path = "../k-launcher-config" }
k-launcher-kernel = { path = "../k-launcher-kernel" }
k-launcher-os-bridge = { path = "../k-launcher-os-bridge" }
tokio = { workspace = true }
