[package]
name = "k-launcher-kernel"
version = "0.2.0"
edition = "2024"

[dependencies]
futures = "0.3"
k-launcher-domain = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
k-launcher-domain = { workspace = true }
plugin-calc = { workspace = true }
plugin-cmd = { workspace = true }
tokio = { workspace = true }
