[package]
name = "plugin-url"
version = "0.2.1"
edition = "2024"

[lib]
name = "plugin_url"
path = "src/lib.rs"

[[bin]]
name = "k-launcher-plugin-url"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
